/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/FullHouseRender.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[1383.89, 65.23, -96.28]}
        rotation={[-Math.PI / 2, 0, 1.57]}
        scale={[4.42, 4.26, 4.26]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material12.geometry}
          material={materials["Material12.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material15.geometry}
          material={materials["Material15.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material17.geometry}
          material={materials["Material17.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material17001.geometry}
          material={materials["Material17.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials["Material2.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material20.geometry}
          material={materials["Material20.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material21.geometry}
          material={materials["Material21.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material22.geometry}
          material={materials["Material22.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material23.geometry}
          material={materials["Material23.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material24.geometry}
          material={materials["Material24.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material28.geometry}
          material={materials["Material28.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material33.geometry}
          material={materials["Material33.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material38.geometry}
          material={materials["Material38.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4.geometry}
          material={materials["Material4.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material6.geometry}
          material={materials["Material6.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material10.geometry}
          material={materials["Material10.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material45.geometry}
          material={materials["Material45.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material11.geometry}
          material={materials["Material9.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material9.geometry}
          material={materials["Material9.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material42.geometry}
          material={materials["Material42.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material8.geometry}
          material={materials["Material8.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material46.geometry}
          material={materials["Material46.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material5.geometry}
          material={materials["Material5.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material40.geometry}
          material={materials["Material40.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials["Material3.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material1.geometry}
          material={materials["Material1.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material41.geometry}
          material={materials["Material41.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material7.geometry}
          material={materials["Material7.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material31.geometry}
          material={materials["Material31.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material44.geometry}
          material={materials["Material44.003"]}
          position={[-0.02, 0, 0.05]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials.Material33}
        position={[-3.85, 9.98, -3.59]}
        scale={1.92}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sky002.geometry}
        material={materials.Color_M08}
        position={[-6.43, 4.12, -6.21]}
        rotation={[3.14, 0, 0]}
        scale={[1.89, 1.89, 1.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bottom_house.geometry}
        material={materials.Color_M09}
        position={[21.36, 31.57, -2.9]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sky008.geometry}
        material={materials.Material21}
        position={[-112.92, 37.98, 12.85]}
        rotation={[-1.58, -0.03, 1.56]}
        scale={[0.85, 0.85, 0.78]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sky004.geometry}
        material={materials.Material33}
        position={[5, 4.5, -2.6]}
        rotation={[-0.01, 0, 3.13]}
        scale={[2.1, 2.1, 1.93]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sky005.geometry}
        material={materials.Material21}
        position={[-112.89, 38.05, -18.38]}
        rotation={[-1.58, -0.02, 1.56]}
        scale={[0.85, 0.85, 0.78]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sky001.geometry}
        material={materials["Asphalt_New.004"]}
        position={[-130.52, 43.69, -2.33]}
        rotation={[-1.58, 0, 1.57]}
        scale={[1.11, 1.11, 1.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sky003.geometry}
        material={materials["Asphalt_New.005"]}
        position={[145.43, 37.09, -3.05]}
        rotation={[1.57, 0.01, -1.58]}
        scale={[0.95, 0.95, 0.87]}
      />
    </group>
  );
}

useGLTF.preload("/FullHouseRender.gltf");
